Fix fractional unroll_length
HorizonRobotics/alf pull request #1358
Opened 2022-06-29 18:59 UTC by emailweixu

There are two bugs for fractional_unroll:
1. replay_buffer is None for train_from_replay_buffer
2. missing summary for unroll under certain condition

Also support interactionless training at the end. The main purpose of this is to train more on the last environmental steps.

2022-06-29 20:16 UTC, le-horizon requested changes
Almost good.

Need to update `common.compute_summary_or_eval_interval` which still relies on the two termination conditions being exclusive.

Thanks,
Le

2022-06-29 22:14 UTC, emailweixu commented
> Almost good.
> 
> Need to update `common.compute_summary_or_eval_interval` which still relies on the two termination conditions being exclusive.
> 
> Thanks, Le

Good catch. Fixed.

2022-06-30 06:15 UTC, le-horizon submitted a review, later dismissed
LG thanks for the fixes, Wei.

2022-06-30 17:37 UTC, hnyu commented on alf/trainers/policy_trainer.py
> +                    or (not self._num_iterations and self._num_env_steps
no need to `and self._num_env_steps` because it has to be >0 in this case.

2022-06-30 22:33 UTC, hnyu approved these changes

2022-06-30 22:49 UTC, merged