alf.import_config()
HorizonRobotics/alf pull request #1476
Opened 2023-04-11 03:09 UTC by emailweixu

There are two motivations for this:

1. config files can be correctly loaed after alf.reset_configs(). Previously, because python only run the imported file once, so after alf.reset_configs(), the config set in the imported file will not be set.

2. save the imported config files. Imported config files are not saved in previous code.

2023-04-11 04:02 UTC, hnyu requested changes

2023-04-11 04:02 UTC, hnyu commented on alf/examples/sac_cart_pole_conf.py
> +alf.import_config("sac_conf.py")
Now how we should provide the path to the conf file? Seems not as straightforward as importing a module.

2023-04-11 04:02 UTC, hnyu commented on alf/config_util.py
> +def _get_conf_file_full_path(conf_file):
Comment on the rough logic of how the full path is obtained for the conf file.

2023-04-11 04:02 UTC, hnyu commented on alf/config_util.py
> +    """Import the config from another file.
What will happen if `import_config` and the old `import` are used in a mixed way?

2023-04-11 04:02 UTC, hnyu commented on alf/config_util.py
> +def load_config(conf_file):
It could be very easy to confuse this function with `import_config`. Should add explanations of their difference.

2023-04-11 04:02 UTC, hnyu commented on alf/environments/parallel_environment.cpp
> +  if (arrays.size() != sizes_.size()) {
This is just checking the sizes but not specs?

2023-04-11 04:02 UTC, hnyu commented on alf/utils/common.py
> +        seed = hash(str(os.getpid()) + '|' + str(time.time()))
It is hard to guarantee that other envs (not gym) can accept a negative random seed.

2023-04-12 18:01 UTC, hnyu commented on alf/config_util.py
>          return candidate
Should we by default set ALF_CONFIG_PATH to alf_root? So that any config file under alf root can be found by providing relative paths.

2023-04-12 18:16 UTC, emailweixu commented on alf/config_util.py
> +def _get_conf_file_full_path(conf_file):
comment added to load_config and import_config

2023-04-12 18:16 UTC, emailweixu commented on alf/config_util.py
> +    """Import the config from another file.
That still works most of time. The time it fails is when ``import_config()`` is called from a file A that is loaded by file B using ``import`` and the A and B are not in the same directory.

2023-04-12 18:16 UTC, emailweixu commented on alf/config_util.py
> +def load_config(conf_file):
added

2023-04-12 18:16 UTC, emailweixu commented on alf/environments/parallel_environment.cpp
> +  if (arrays.size() != sizes_.size()) {
updated

2023-04-12 18:16 UTC, emailweixu commented on alf/utils/common.py
> +        seed = hash(str(os.getpid()) + '|' + str(time.time()))
added ``abs()``

2023-04-12 18:16 UTC, emailweixu commented on alf/examples/sac_cart_pole_conf.py
> +alf.import_config("sac_conf.py")
In this case "sac_conf.py" is in the same directory as "sac_cart_pole_conf.py", so simply "sac_conf.py" works. Added more explanation in ``import_config``

2023-04-12 18:19 UTC, emailweixu commented on alf/config_util.py
>          return candidate
I have the impression that the relative import from the directory obtained from line 834-839 can cover our existing use cases.

2023-04-12 23:20 UTC, hnyu commented on alf/config_util.py
>          return candidate
> I have the impression that the relative import from the directory obtained from line 834-839 can cover our existing use cases.

What if I have two conf files: `~/alf/configs/path1/conf1.py` and `~/alf/configs/path2/conf2.py`, and I want to import `conf1.py` in `conf2.py`? I can provide `../path1/conf1.py` but if the path is deep sometimes, it's better to directly start with the repo root as `configs/path1/conf1.py`.

2023-04-12 23:59 UTC, emailweixu commented on alf/config_util.py
>          return candidate
I agree with your example. But currently, we don't have that kind of config in our repo.  And if that is needed, one can always set ALF_CONFIG_PATH himself.

2023-04-13 03:20 UTC, hnyu approved these changes

2023-04-13 04:38 UTC, merged