add action clipping wrapper
HorizonRobotics/alf pull request #470
Opened 2020-03-18 21:12 UTC by hnyu

tested with sac

2020-03-18 23:00 UTC, emailweixu requested changes

2020-03-18 23:00 UTC, emailweixu commented on alf/environments/torch_wrappers.py
> +        if action_spec.is_continuous:
action_spec might be nested

2020-03-19 20:59 UTC, Haichao-Zhang commented on alf/environments/torch_wrappers.py
> +                    action = torch.max(
Might be able to use the function from spec_util.py:
https://github.com/HorizonRobotics/alf/blob/b1988ee0fa0a242263ed63ec014249664d8c48ba/alf/utils/spec_utils.py#L60-L70

2020-03-19 22:26 UTC, emailweixu submitted a review, later dismissed

2020-03-19 22:50 UTC, hnyu commented
resolve conflicts

2020-03-20 00:10 UTC, Haichao-Zhang approved these changes

2020-03-20 00:16 UTC, merged