Carla navigation sensor
HorizonRobotics/alf pull request #602
Opened 2020-06-20 01:15 UTC by emailweixu

2020-06-20 08:16 UTC, le-horizon submitted a review, later dismissed
Took a quick look, and looks good.  Let's merge it in~

2020-06-20 08:16 UTC, le-horizon commented on alf/environments/suite_carla.py
> +    Note that the route is fixed (not change based on current vehicale location)
->vehicle

2020-06-23 17:49 UTC, hnyu requested changes

2020-06-23 17:49 UTC, hnyu commented on alf/environments/suite_carla.py
> +        """
comment

2020-06-23 17:49 UTC, hnyu commented on alf/environments/suite_carla.py
> +        """Get the current observation.
More descriptive? Might copy `observation_desc` here. Also explain the observation spec.

2020-06-23 17:49 UTC, hnyu commented on alf/environments/suite_carla.py
> +    `initial_distance / min_speed `.
\``

2020-06-23 17:49 UTC, hnyu commented on alf/environments/suite_carla.py
> +    1. Arriving goal:  `success_reward`
\``

2020-06-25 21:08 UTC, hnyu approved these changes

2020-06-25 21:12 UTC, merged