KLD regularized SAC
HorizonRobotics/alf pull request #624
Opened 2020-07-13 18:36 UTC by emailweixu

Also generate a scalar summary for action mean.

2020-07-13 20:26 UTC, Haichao-Zhang commented on alf/algorithms/prior_actor.py
> +                 name="PriorActor"):
name="UniformPriorActor"

2020-07-13 20:26 UTC, Haichao-Zhang commented on alf/algorithms/sac_algorithm.py
> +                 target_kld_per_dim=3.,
May be useful to add a note that target_kld_per_dim  will be used to update self._target_entropy value when prior_actor is used.

2020-07-13 23:31 UTC, Haichao-Zhang reviewed
LGTM. Just two more minor comments on the newly added commit.

2020-07-13 23:31 UTC, Haichao-Zhang commented on alf/algorithms/sac_algorithm.py
> +            target_kld_per_dim (float): ``alpha`` is dynamically ajusted so that
ajusted -> adjusted

2020-07-13 23:31 UTC, Haichao-Zhang commented on alf/algorithms/sac_algorithm.py
> +        :math:`E_\pi(\sum_t \gamma^t(r_t + \alpha D_{\rm KL}(\pi(\cdot)|s_t)||\pi^0(\cdot)|s_t)))`
```r_t + \alpha D_{\rm KL}``` -> should be ```r_t - \alpha D_{\rm KL}```

2020-07-13 23:39 UTC, hnyu requested changes

2020-07-13 23:39 UTC, hnyu commented on alf/algorithms/prior_actor.py
> +        torch.erf(0.7071067811865476 * b) - torch.erf(0.7071067811865476 * a))
use the variable to hold this constant as it appears twice?

2020-07-13 23:39 UTC, hnyu commented on alf/algorithms/prior_actor.py
> +    """
Description of what this class does

2020-07-13 23:39 UTC, hnyu commented on alf/algorithms/prior_actor.py
> +class PriorActor(Algorithm):
The name of this class could be better. Right now it sounds like a general class of "uniformprioractor", but it's actually quite different.

2020-07-13 23:39 UTC, hnyu commented on alf/algorithms/sac_algorithm.py
> +    where :math:`pi^0` is the prior actor.
This paragraph should be moved to below "points different"

2020-07-14 00:54 UTC, Haichao-Zhang submitted a review, later dismissed

2020-07-14 01:04 UTC, emailweixu commented on alf/algorithms/prior_actor.py
> +        torch.erf(0.7071067811865476 * b) - torch.erf(0.7071067811865476 * a))
Changed. Though I believe it will be a little bit slower.

2020-07-14 01:04 UTC, emailweixu commented on alf/algorithms/prior_actor.py
> +    """
Updated

2020-07-14 01:04 UTC, emailweixu commented on alf/algorithms/prior_actor.py
> +class PriorActor(Algorithm):
updated

2020-07-14 01:04 UTC, emailweixu commented on alf/algorithms/sac_algorithm.py
> +    where :math:`pi^0` is the prior actor.
moved

2020-07-14 01:40 UTC, hnyu approved these changes

2020-07-14 03:45 UTC, merged