MuZero algorithm
HorizonRobotics/alf pull request #643
Opened 2020-08-03 23:48 UTC by emailweixu

This PR contains two commits. The first one is the full MuZero algorithm. The second one is for speeding up MCTSAlgorithm.

2020-08-04 21:06 UTC, Haichao-Zhang requested changes

2020-08-04 21:06 UTC, Haichao-Zhang commented on alf/algorithms/mcts_algorithm_test.py
> +        super().__init__()
TicTacToeModel has some repeated code with TicTacToeEnv. Is it a good idea to reduce it, for example, by leveraging an env instance for implementing TicTacToeModel?

2020-08-04 21:06 UTC, Haichao-Zhang commented on alf/algorithms/mcts_algorithm.py
> +            - path_lenghts: [B] vector, length of each search path
path_lengths

2020-08-04 21:06 UTC, Haichao-Zhang commented on alf/algorithms/mcts_algorithm.py
> +    """Helper function for creating MCTSAlgorithm for atari games."""
atari games -> control

2020-08-04 21:06 UTC, Haichao-Zhang commented on alf/algorithms/muzero_algorithm.py
> +                to constrcut the model. The model should follow the interface
construct

2020-08-04 21:06 UTC, Haichao-Zhang commented on alf/algorithms/muzero_algorithm.py
> +                at the last step to caculate the return.
caculate  -> calculate

2020-08-04 21:06 UTC, Haichao-Zhang commented on alf/algorithms/muzero_algorithm.py
> +                state=scale_gradient(model_output.state, 0.5))
Might be useful to make this 0.5 to be configurable?

2020-08-04 21:06 UTC, Haichao-Zhang commented on alf/algorithms/mcts_algorithm_test.py
> +        player1_won = ((lines == -1).sum(dim=2) == 3).any(dim=1)
player1_won / player2_won -> player0_won / player1_won

2020-08-05 23:08 UTC, emailweixu commented on alf/algorithms/mcts_algorithm.py
> +            - path_lenghts: [B] vector, length of each search path
fixed

2020-08-05 23:08 UTC, emailweixu commented on alf/algorithms/mcts_algorithm.py
> +    """Helper function for creating MCTSAlgorithm for atari games."""
fixed

2020-08-05 23:08 UTC, emailweixu commented on alf/algorithms/mcts_algorithm_test.py
> +        super().__init__()
I am aware of that. But decided not to do that for two reasons:
1. It will make code structure more complex
2. This is not likely to be reused anyway.

2020-08-05 23:08 UTC, emailweixu commented on alf/algorithms/mcts_algorithm_test.py
> +        player1_won = ((lines == -1).sum(dim=2) == 3).any(dim=1)
updated.

2020-08-05 23:08 UTC, emailweixu commented on alf/algorithms/muzero_algorithm.py
> +                to constrcut the model. The model should follow the interface
fixed

2020-08-05 23:08 UTC, emailweixu commented on alf/algorithms/muzero_algorithm.py
> +                at the last step to caculate the return.
fixed

2020-08-05 23:08 UTC, emailweixu commented on alf/algorithms/muzero_algorithm.py
> +                state=scale_gradient(model_output.state, 0.5))
added.

2020-08-06 04:09 UTC, Haichao-Zhang submitted a review, later dismissed

2020-08-06 07:24 UTC, Haichao-Zhang submitted a review, later dismissed

2020-08-07 22:46 UTC, Haichao-Zhang approved these changes

2020-08-07 23:54 UTC, merged