Scheduler
HorizonRobotics/alf pull request #652
Opened 2020-08-14 07:17 UTC by emailweixu

Support target entropy scheduling and learning rate scheduling

2020-08-14 23:34 UTC, hnyu requested changes

2020-08-14 23:34 UTC, hnyu commented on alf/trainers/policy_trainer.py
> -        finally:
Why making this change? Currently it will save the checkpoint if an error occurs, which is good.

2020-08-14 23:34 UTC, hnyu commented on alf/utils/schedulers.py
> +            while index > 0 and progress < progresses[index - 1]:
In what situation we need to backstep the index? It seems that the progress is always incrementing

2020-08-14 23:34 UTC, hnyu commented on alf/utils/schedulers.py
> +            schedule (list[tuple]): each tuple is a pair of (progress, value)
This comment is still for stepscheduler.

2020-08-14 23:40 UTC, Haichao-Zhang commented on alf/utils/schedulers.py
> +                the current value will be value.
the current value -> a linearly interpolated value

2020-08-15 00:39 UTC, Haichao-Zhang submitted a review, later dismissed

2020-08-15 00:43 UTC, hnyu commented on alf/utils/schedulers.py
> +                value[i] will be used. progress[0] must be 0.
Maybe also add a sentence about if the current progress is greater than progress[-1]? (then it's always the same last value)

2020-08-15 02:16 UTC, hnyu approved these changes

2020-08-15 03:50 UTC, merged