Network building utilities
HorizonRobotics/alf pull request #760
Opened 2021-01-22 23:39 UTC by emailweixu

Introduces alf.nn.Sequential, alf.nn.Parallel and alf.nn.Branch

See containers_test.py for example

2021-01-25 21:39 UTC, Haichao-Zhang requested changes

2021-01-25 21:39 UTC, Haichao-Zhang commented on alf/algorithms/encoding_algorithm.py
> +                 encoder=None,
Can add comments to  ``encoder`` in ``Args:`` section  and its connection with ``encoder_cls``.

2021-01-25 21:39 UTC, Haichao-Zhang commented on alf/networks/networks.py
> +        self._block = block
self._activation = activation

2021-01-25 21:39 UTC, Haichao-Zhang commented on alf/networks/networks.py
> +        return torch.relu_(x + y), state
torch.relu_ -> self._activation

2021-01-25 21:39 UTC, Haichao-Zhang commented on alf/networks/containers.py
> +            Sequential:
Sequential  -> Parallel

2021-01-25 21:39 UTC, Haichao-Zhang commented on alf/networks/containers.py
> +            Sequential:
Sequential  -> Branch

2021-01-25 23:25 UTC, Haichao-Zhang submitted a review, later dismissed

2021-01-25 23:58 UTC, hnyu requested changes

2021-01-25 23:58 UTC, hnyu commented on alf/nest/utils.py
> +        elif not isinstance(nested, torch.nn.Module):
Why creating an empty module in this case?

2021-01-25 23:58 UTC, hnyu commented on alf/networks/containers.py
> +    def __init__(self, layers, input_tensor_spec=None, name="Sequential"):
layers -> modules

2021-01-25 23:58 UTC, hnyu commented on alf/networks/containers.py
> +    def __init__(self, networks, input_tensor_spec=None, name="Parallel"):
We should probably unify the argument names as either modules or networks. Right now Sequential call it layers.

2021-01-25 23:58 UTC, hnyu commented on alf/networks/encoding_networks.py
> -            (self._preprocessing_combiner == math_ops.identity or isinstance(
What if someone provides math_ops.identity ?

2021-01-25 23:58 UTC, hnyu commented on alf/networks/networks.py
> +class LSTMCell(Network):
Can we directly wrap the pytorch one? https://pytorch.org/docs/stable/generated/torch.nn.LSTMCell.html

2021-01-25 23:58 UTC, hnyu commented on alf/networks/networks.py
> +class GRUCell(Network):
https://pytorch.org/docs/1.4.0/nn.html#torch.nn.GRU

2021-01-26 01:17 UTC, emailweixu commented on alf/algorithms/encoding_algorithm.py
> +                 encoder=None,
removed encoder.

2021-01-26 01:17 UTC, emailweixu commented on alf/networks/containers.py
> +            Sequential:
Fixed.

2021-01-26 01:17 UTC, emailweixu commented on alf/networks/networks.py
> +        self._block = block
fixed.

2021-01-26 01:17 UTC, emailweixu commented on alf/networks/networks.py
> +        return torch.relu_(x + y), state
fixed.

2021-01-26 01:17 UTC, emailweixu commented on alf/networks/containers.py
> +            Sequential:
fixed

2021-01-26 02:08 UTC, emailweixu commented on alf/nest/utils.py
> +        elif not isinstance(nested, torch.nn.Module):
Changed to use None

2021-01-26 02:08 UTC, emailweixu commented on alf/networks/containers.py
> +    def __init__(self, layers, input_tensor_spec=None, name="Sequential"):
changed

2021-01-26 02:08 UTC, emailweixu commented on alf/networks/containers.py
> +    def __init__(self, networks, input_tensor_spec=None, name="Parallel"):
Changed to modules.

2021-01-26 02:08 UTC, emailweixu commented on alf/networks/encoding_networks.py
> -            (self._preprocessing_combiner == math_ops.identity or isinstance(
In that case, flow goes to the else branch.

2021-01-26 02:08 UTC, emailweixu commented on alf/networks/networks.py
> +class LSTMCell(Network):
The docstring of torch.nn.LSTMCell won't show in the subclass. Is there a easy way using the docstring of torch.nn.LSTMCell?

2021-01-26 02:21 UTC, hnyu commented on alf/nest/utils.py
> +            module = None
The comment in docstring needs to change to "None"

2021-01-26 02:21 UTC, hnyu commented on alf/networks/networks.py
> +class LSTMCell(Network):
Haven't done this before. Not sure if this is a workaround https://github.com/sphinx-doc/sphinx/issues/3140

2021-01-26 02:25 UTC, hnyu commented on alf/networks/encoding_networks.py
> -            (self._preprocessing_combiner == math_ops.identity or isinstance(
But we should support it by ParallelEncodingNetwork?

2021-01-27 02:58 UTC, emailweixu commented on alf/nest/utils.py
> +            module = None
changed

2021-01-27 02:58 UTC, emailweixu commented on alf/networks/networks.py
> +class LSTMCell(Network):
It will be quite hacky. ``torch.nn.LSTMCell.__doc__`` contains all the doc, including the examples. The examples does not match our usage.

2021-01-27 04:44 UTC, hnyu approved these changes

2021-01-27 04:50 UTC, Haichao-Zhang approved these changes

2021-01-27 20:13 UTC, merged