More net building utilities
HorizonRobotics/alf pull request #800
Opened 2021-03-05 02:37 UTC by emailweixu

Also
* change alf.nn.Sequential to follow the interface of torch.nn.Sequentil
* Improved PredictiveRepresentationLearner for supporting post_processor and non-replay buffer based training when num_unrolll_steps==0

2021-03-05 22:52 UTC, Haichao-Zhang commented on alf/networks/containers.py
> +            modules (nn.Module): list of ``torch.nn.Module`` or ``alf.nn.Network``.
The comment in (), i.e. ``(nn.Module) `` should be updated?

2021-03-05 22:52 UTC, Haichao-Zhang commented on alf/algorithms/predictive_representation_learner.py
> +                if ``num_unroll_steps`` of 0 means no future prediction and hence
can remove ``if``

2021-03-05 22:52 UTC, Haichao-Zhang commented on alf/layers.py
> +                    "Network element of layers.Sequential should stateless. "
should be

2021-03-05 22:52 UTC, Haichao-Zhang commented on alf/algorithms/predictive_representation_learner.py
> +                where ``latent`` is the output from encoding_net.
Is it useful to provide an option to specify postprocessor optimizer, to be structurally similar to ``encoding_net`` and ``dynamics net``? Might not be necessary in most of the cases when view postprocessor as part of the downstream networks, but might be useful in some cases.

2021-03-06 00:07 UTC, hnyu requested changes

2021-03-06 00:07 UTC, hnyu commented on alf/algorithms/predictive_representation_learner.py
> +        loss = loss.reshape(*predicted.shape[:2], *loss.shape[1:])
Why bothering reshaping here? I believe the loss class can handle arbitrary shapes.

2021-03-06 00:07 UTC, hnyu commented on alf/layers.py
> +        self._networks = modules
It's confusing that the variable name is "networks" but in fact it can't contain any network

2021-03-06 00:07 UTC, hnyu commented on alf/networks/containers.py
> +    # want to use *modules here to make the interface consistant with
consistent

2021-03-06 00:07 UTC, hnyu commented on alf/networks/containers.py
> +def Sequential(*modules, input_tensor_spec=None, name="Sequential"):
Should still keep "configurable"?

2021-03-06 00:07 UTC, hnyu commented on alf/networks/containers.py
> +                the block.input_tensor_spec[0] or input_tensor_spec['input']
\``block.input_tensor_spec['input']\``

2021-03-06 01:53 UTC, Haichao-Zhang approved these changes

2021-03-08 19:07 UTC, emailweixu commented on alf/algorithms/predictive_representation_learner.py
> +        loss = loss.reshape(*predicted.shape[:2], *loss.shape[1:])
CrossEntropyLoss does not behave as we expected. The shape of predicted is [T, B, N] and the shape of target is [T, B], where N is the number of categories. For this kind of multidimensional tensor, CrossEntropyLoss expect shapes like [T, N, B] and [T, B]

2021-03-08 19:07 UTC, emailweixu commented on alf/algorithms/predictive_representation_learner.py
> +                where ``latent`` is the output from encoding_net.
added.

2021-03-08 19:07 UTC, emailweixu commented on alf/algorithms/predictive_representation_learner.py
> +                if ``num_unroll_steps`` of 0 means no future prediction and hence
removed

2021-03-08 19:07 UTC, emailweixu commented on alf/layers.py
> +        self._networks = modules
self._modules is already used nn.Module

2021-03-08 19:07 UTC, emailweixu commented on alf/layers.py
> +                    "Network element of layers.Sequential should stateless. "
fixed

2021-03-08 19:07 UTC, emailweixu commented on alf/networks/containers.py
> +def Sequential(*modules, input_tensor_spec=None, name="Sequential"):
As far as I know, none of existing gin files uses this. New configs should be written in python. So there is no need for it to be configurable.

2021-03-08 19:07 UTC, emailweixu commented on alf/networks/containers.py
> +            modules (nn.Module): list of ``torch.nn.Module`` or ``alf.nn.Network``.
``nn.Module`` in the parenthesis is the type of each module.

2021-03-08 22:35 UTC, hnyu approved these changes

2021-03-08 22:41 UTC, merged