[Small] Disable summary for non-master processes in DDP training mode
HorizonRobotics/alf pull request #954
Opened 2021-07-30 23:07 UTC by breakds

# Description

Similar to only having process 0 (master process) writing checkpoint, we want to have only process 0 writing the summary. This is done by not enabling  summary unless the process rank is 0 (or -1) when setting up `PolicyTrainer`.

# Testing

Tested training in dual GPU settings with this PR. There are still 2 events file generated but only one is being written to.

2021-07-30 23:35 UTC, emailweixu requested changes

2021-07-30 23:35 UTC, emailweixu commented on alf/trainers/policy_trainer.py
> +        if self._rank <= 0:
In Algorithm._train_experience(), enable_summary() is also called, so this will not be effective.

2021-07-30 23:39 UTC, emailweixu commented on alf/trainers/policy_trainer.py
> +        if self._rank <= 0:
You may consider to change run_under_record_context so that _cond() always returns False.

2021-08-02 19:22 UTC, breakds commented
Based on the feedback, I will replace this PR with a new one.

2021-08-02 19:22 UTC, closed without merging