Procgen Integration (#984)
HorizonRobotics/alf pull request #987
Opened 2021-08-25 18:30 UTC by breakds

# Motivation

In PPG and maybe other baseline algorithms the authors use [procgen](https://github.com/openai/procgen) as the benchmarking environment. To be able to test our implementations and algorithms on such environment as well, we should add procgen into the suite of environments as well.

However, `procgen` itself is a [gym3](https://github.com/openai/gym3/) based environment which is slightly different from `gym`, even though it provides a compatible layer to `gym`. We need to bridge the gap.

# Solution

`procgen` works out of the box in alf **for training** thanks to its `gym` compatible layer interface. However, there is a gap on rendering - for `gym3` based environments `render()` does nothing and if we want to render it we will need to do it at the construction time.

@hnyu  and I had a discussion and proposed a work around with an environment wrapper. In detail:

1. The wrapper `AlfGym3Wrapper` hijacks the `render()` function. When `render()` is called the first time, it will reconstruct the underlying environment with correct arguments that enables rendering.
2. Ask the `render()` to return the underlying `rgb_array` frame for recording purposes.
3. For `suite_gym`, it will automatically wrap the environment with the above `AlfGym3Wrapper` if it detects the underlying environment is a `procgen` env.

So that the whole process becomes transparent to the user. See the `procgen_conf.py` for an example of how to use it (without seeing the dirty work behind it).

# Testing

Tested with `ActorCriticAlgorithm` on 2 procgen environments `coinrun` and `bigfish` with training, testing and recording.

1. The configuration `ac_procgen_bigfish.py` and `ac_procgen_coinrun.py` aren't in the PR because the trained models are not good. However they were able to demonstrate that `procgen` environment works which is the purpose of this PR.
2. Recorded play movies are attached. Note that for bigfish it learned the trivial policy (lol)

https://user-images.githubusercontent.com/1111035/130845728-44ae7787-5ffd-41cd-bd60-e2e9eb5ca503.mp4

https://user-images.githubusercontent.com/1111035/130845533-05fa1343-e37b-4780-8ed6-42a11909b8cc.mp4

2021-08-25 18:32 UTC, breakds commented
I think I am still going to need to add `procgen` to the dependencies in `setup.py` and multiple `requirements.txt`. Other than that the PR is ready for review.

2021-08-25 19:35 UTC, hnyu requested changes

2021-08-25 19:35 UTC, hnyu commented on alf/environments/alf_gym3_wrapper.py
> +class AlfGym3Wrapper(AlfEnvironmentBaseWrapper):
This class should inherit gym.Wrapper https://github.com/openai/gym/blob/3abd5d55afa9c43fe5f7da2b1a42f064c14127b0/gym/core.py#L208 because it doesn't involve any ALF data structures. 

And its name doesn't have to include ALF. Maybe just Gym3RenderWrapper? 

(see https://alf-fork.readthedocs.io/en/latest/tutorial/environments_and_wrappers.html and https://alf-fork.readthedocs.io/en/latest/tutorial/environments_and_wrappers.html#alfenvironmentbasewrapper for the difference between wrappers)

2021-08-25 19:35 UTC, hnyu commented on alf/environments/alf_wrappers.py
> +    def replace_wrapped_env(self, new_env):
As noted above, seems not appropriate to have this in this class.

2021-08-25 20:04 UTC, breakds commented on alf/environments/alf_gym3_wrapper.py
> +class AlfGym3Wrapper(AlfEnvironmentBaseWrapper):
Let me read the tutorial and update the PR.

2021-08-25 20:14 UTC, breakds commented on alf/environments/alf_wrappers.py
> +    def replace_wrapped_env(self, new_env):
I am so glad that I don't have to add this function. Thank you!

2021-08-25 21:02 UTC, breakds commented
PR is updated and tested again. PTAL.

2021-08-25 21:18 UTC, hnyu requested changes

2021-08-25 21:18 UTC, hnyu commented on alf/environments/gym_wrappers.py
> +                self.env.spec.make(render=(mode == 'human'), render_mode=mode))
Why pass in render=False when mode!="human"?

2021-08-25 21:18 UTC, hnyu commented on alf/environments/gym_wrappers.py
> +        wrapped_env = self.env.env
Should be OK to just use `self.env`. In fact there might be a sequence of wrappers, so Gym already makes sure to forward the call recursively. See

https://github.com/openai/gym/blob/bb81e141ea7ae67ce339109095841592e8231185/gym/core.py#L228

2021-08-25 21:18 UTC, hnyu commented on alf/environments/suite_gym.py
> +        gym_env = gym_wrappers.Gym3RenderWrapper(gym_env)
Could potentially make Gym3RenderWrapper do nothing if gym_env is not gym3. So we don't have to check its id (not flexible).

2021-08-25 21:36 UTC, breakds commented on alf/environments/gym_wrappers.py
> +                self.env.spec.make(render=(mode == 'human'), render_mode=mode))
Because `render=True` means rendering on the screen in `gym3`. It should only be turned on when `render(mode='human')`.

2021-08-25 21:42 UTC, breakds commented on alf/environments/gym_wrappers.py
> +        wrapped_env = self.env.env
Normally yes. But in this case `self.env` is `gym3.interop.ToGymEnv`, and `self.env.env` is `gym3.viewer.ViewerWrapper`. This mean that they are `gym3` wrappers that does not follow the convention. Therefore this is like specialized code logic for `gym3`.

I tested `self.env` does not work before adding this.

2021-08-25 21:47 UTC, breakds commented on alf/environments/suite_gym.py
> +        gym_env = gym_wrappers.Gym3RenderWrapper(gym_env)
Acknowledged but,

1. I think "not wrapping it" is better than "having a wrapper that does nothing" for none-gym3 environments
2. Do not get what does "flexible" mean here - are you suggesting "in the case when there are non gym3 environments whose name starts with `procgen`, this will be broken"? If so I do agree. I can switch it to checking the type of it.

2021-08-25 21:49 UTC, hnyu commented on alf/environments/suite_gym.py
> +        gym_env = gym_wrappers.Gym3RenderWrapper(gym_env)
> Acknowledged but,
> 
> 1. I think "not wrapping it" is better than "having a wrapper that does nothing" for none-gym3 environments
> 2. Do not get what does "flexible" mean here - are you suggesting "in the case when there are non gym3 environments whose name starts with `procgen`, this will be broken"? If so I do agree. I can switch it to checking the type of it.

If in the future there are other environments written by gym3 then we need to remember to add checks for those environment names, which is trouble,

2021-08-25 21:51 UTC, breakds commented on alf/environments/suite_gym.py
> +        gym_env = gym_wrappers.Gym3RenderWrapper(gym_env)
Btw, I remembered now that I was trying to avoid `import gym3` if it is not necessary - that is why the previous implementation was on checking the prefix in the environment id.

2021-08-26 00:03 UTC, hnyu approved these changes

2021-08-27 01:15 UTC, breakds commented
With the updated docker image, CI passed. Will merge now. Thanks for the help, @hnyu !

2021-08-27 01:15 UTC, merged